# 结果文件路径
resfilepath: "E:\\Project\\didi\\Phase2\\DATA\\20230602155520\\final_vdr_analysis.txt"

# 参考结果文件路径
reffilepath: "E:\\Project\\didi\\Phase2\\DATA\\20230602155520\\final_gnss_analysis.txt"

# 分隔符配置，空格为默认分隔符，只需添加即可
delimiter: [",", ":", ";"]

# 作图参数设置

## 这里给出不同做图类型的属性配置， 目前有： 曲线图

## plot 曲线图配置
# type: "plot"
# title: "abc"
# xlabel: "x"
# ylabel: "y"
# linestyle: "--"
# linewidth: 1
# marker: "o"
# markersize: 1
# color: "b"
# figname:

##################################################        单Axes作图设置         #############################################
SingleAxesConfig:
  # 图一
  - type: "plot"
    title: "定位误差"
    xlabel: "x(s)"
    ylabel: "y(m)"
    linestyle: "--"
    linewidth: 1
    marker: "o"
    markersize: 1
    color: "b"
    figname: "E:\\mashuo\\python\\plt\\fig\\位置误差.png"

  # 图二
  - type: "plot"
    title: "速度误差"
    xlabel: "x(s)"
    ylabel: "y(m/s)"
    linestyle: "--"
    linewidth: 1
    marker: "o"
    markersize: 1
    color: "b"
    figname: "E:\\mashuo\\python\\plt\\fig\\速度误差.png"

  # 图三
  - type: "plot"
    title: "航向角误差"
    xlabel: "x(s)"
    ylabel: "y(deg)"
    linestyle: "--"
    linewidth: 1
    marker: "o"
    markersize: 1
    color: "b"
    figname: "E:\\mashuo\\python\\plt\\fig\\航向角误差.png"

############################################## 多Axes作图设置(坐标区属性设置按行排列,即先从左到右，后从上到下) #########################
# 目前尚未扩展
MulAxesConfig:
  # 图一
  - AxesShape: [2, 2]
    title: ["1", "2", "3", "4"]
    xlabel: ["x", "x", "x", "x"]
    ylabel: ["y", "y", "y", "y"]
